### ISSUE TITLE
Invalid Form Parameters after MandrillApp callback

### ISSUE THREAD

**Issue by tabletguy** [JMAConsulting/biz.jmaconsulting.mte#92]
Joomla 3.4.3 on Apache   PHP 5.5.27, MySql 5.5.42-cll, Joomla Database: MySqli
Extension version 2.0 installed.

Callback from MandrillApp is generating this error message. Please let me know if I should be posting this to CiviCRM instead of here. Since it seems to be originating from a MandrillApp post, I'm first guessing that it's related to this extension. Sorry if I've guessed wrong.

-------------------------------------------------------------------

There was a CiviCRM error at AHYMSIN.
Date: 2015-07-21T11:59:59-05:00

***ERROR***
Array
(
    [type] => 8192
    [message] => mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead
    [file] => /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/packages/DB/mysql.php
    [line] => 241
)
Array
(
    [message] => Invalid form parameters.
    [code] =>
)

***LOGGED IN USER***
count:              25
is_error:           1
error_message:      Expected one Contact but found 25

***SERVER***
PATH:               /sbin:/usr/sbin:/bin:/usr/bin:/usr/X11R6/bin
PWD:                /usr/local/cpanel/cgi-sys
SHLVL:              0
SCRIPT_NAME:        /main/index.php
REQUEST_URI:        /main/index.php?option=com_civicrm&task=civicrm/mailing/forward
QUERY_STRING:       option=com_civicrm&task=civicrm/mailing/forward
REQUEST_METHOD:     POST
SERVER_PROTOCOL:    HTTP/1.1
GATEWAY_INTERFACE:  CGI/1.1
REMOTE_PORT:        36815
SCRIPT_FILENAME:    /home/ahymsinc/public_html/main/index.php
SERVER_ADMIN:       webmaster@ahymsin.org
CONTEXT_DOCUMENT_ROOT:/home/ahymsinc/public_html
CONTEXT_PREFIX:
REQUEST_SCHEME:     http
DOCUMENT_ROOT:      /home/ahymsinc/public_html
REMOTE_ADDR:        184.151.111.114
SERVER_PORT:        80
SERVER_ADDR:        184.154.90.58
SERVER_NAME:        ahymsin.org
SERVER_SOFTWARE:    Apache
SERVER_SIGNATURE:
HTTP_COOKIE:        1c817e2e332197c6dfb5ad4ac920a4e3=lnoocjl49i898mhr4pg64amua0
HTTP_ACCEPT_CHARSET:utf-8, iso-8859-1, utf-16, *;q=0.7
HTTP_ACCEPT_LANGUAGE:fr-CA, en-US
HTTP_ACCEPT_ENCODING:gzip,deflate
HTTP_USER_AGENT:    Mozilla/5.0 (Linux; U; Android 4.0.3; fr-ca; A320a Build/IML74K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
HTTP_X_WAP_PROFILE: http://mandrillapp.com/track/click/30163280/www.htcmms.com.tw?p=eyJzIjoiQnA1Q3NHTzJoeWZtc0xfS1pOVy1yZjVqTDVnIiwidiI6MSwicCI6IntcInVcIjozMDE2MzI4MCxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvd3d3Lmh0Y21tcy5jb20udHdcXFwvQW5kcm9pZFxcXC9CZWxsXFxcL0EzMjBhXFxcL3VhLXByb2ZpbGUueG1sXCIsXCJpZFwiOlwiMzc3OTNlZWZmMWE3NDA1NDg2ZGViYzRkNWM4M2FlODRcIixcInVybF9pZHNcIjpbXCI4M2JlNGEwMmFjYzIwMjUzZTI4ZDk3YWExYThjY2RhYzY2NzFlMWJhXCJdfSJ9
HTTP_ACCEPT:        text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
CONTENT_TYPE:       application/x-www-form-urlencoded
HTTP_ORIGIN:        http://mandrillapp.com/track/click/30163280/ahymsin.org?p=eyJzIjoiOGtrVm9mX1VVYzlCcnBaaXZvamoxVWhONFdvIiwidiI6MSwicCI6IntcInVcIjozMDE2MzI4MCxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvYWh5bXNpbi5vcmdcIixcImlkXCI6XCIzNzc5M2VlZmYxYTc0MDU0ODZkZWJjNGQ1YzgzYWU4NFwiLFwidXJsX2lkc1wiOltcIjJkMTVhZjdkZjQ1ZGQxYTExYWQzODJhOTJhNzQyNDQxMjNlYzFhNThcIl19In0
HTTP_CACHE_CONTROL: max-age=0
CONTENT_LENGTH:     455
HTTP_REFERER:       http://mandrillapp.com/track/click/30163280/ahymsin.org?p=eyJzIjoiYjNkdE41aFhTZm9vWmZ1R3J5ZjJBUG1tQVdRIiwidiI6MSwicCI6IntcInVcIjozMDE2MzI4MCxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvYWh5bXNpbi5vcmdcXFwvbWFpblxcXC9jb21wb25lbnRcXFwvY2l2aWNybVxcXC8_aD00OTk0NjZlMTg2Y2FiMzI1JmppZD0xNDgwJmxhbmc9ZW4mcWlkPTM2Nzc0MSZyZXNldD0xJnRhc2s9Y2l2aWNybVxcXC9tYWlsaW5nXFxcL2ZvcndhcmRcIixcImlkXCI6XCIzNzc5M2VlZmYxYTc0MDU0ODZkZWJjNGQ1YzgzYWU4NFwiLFwidXJsX2lkc1wiOltcImZiNGRiZDZjZDk5NDRlMTlmNWFiYmIzM2Q1MGVkYWI4YWE5YjYwM2NcIl19In0
HTTP_CONNECTION:    close
HTTP_HOST:          ahymsin.org
HTTP_AUTHORIZATION:
UNIQUE_ID:          Va56jLiaWjoAADmNMsMAAAAn
FCGI_ROLE:          RESPONDER
PHP_SELF:           /main/index.php
REQUEST_TIME_FLOAT: 1437497996.5513
REQUEST_TIME:       1437497996

***BACKTRACE***
#0 /home/ahymsinc/public_html/main/media/civicrm/custom_ext/ca.bidon.reporterror/reporterror.php(207): reporterror_civicrm_generatereport("AHYMSIN", (Array:2), NULL)
#1 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Core/Error.php(350): reporterror_civicrm_handler((Array:2))
#2 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Mailing/Form/ForwardMailing.php(52): CRM_Core_Error::fatal("Invalid form parameters.")
#3 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Core/Form.php(455): CRM_Mailing_Form_ForwardMailing->preProcess()
#4 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Core/StateMachine.php(140): CRM_Core_Form->buildForm()
#5 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Mailing_Form_ForwardMailing), "next", "Next")
#6 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Mailing_Form_ForwardMailing), "next")
#7 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Mailing_Form_ForwardMailing), "next")
#8 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Core/Controller.php(353): HTML_QuickForm_Page->handle("next")
#9 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Utils/Wrapper.php(115): CRM_Core_Controller->run()
#10 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(286): CRM_Utils_Wrapper->run("CRM_Mailing_Form_ForwardMailing", "Forward Mailing", NULL)
#11 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:15))
#12 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#13 /home/ahymsinc/public_html/main/components/com_civicrm/civicrm.php(86): CRM_Core_Invoke::invoke((Array:3))
#14 /home/ahymsinc/public_html/main/components/com_civicrm/civicrm.php(11): civicrm_invoke()
#15 /home/ahymsinc/public_html/main/libraries/cms/component/helper.php(392): require_once("/home/ahymsinc/public_html/main/components/com_civicrm/civicrm.php")
#16 /home/ahymsinc/public_html/main/libraries/cms/component/helper.php(372): JComponentHelper::executeComponent("/home/ahymsinc/public_html/main/components/com_civicrm/civicrm.php")
#17 /home/ahymsinc/public_html/main/libraries/cms/application/site.php(191): JComponentHelper::renderComponent("com_civicrm")
#18 /home/ahymsinc/public_html/main/libraries/cms/application/site.php(230): JApplicationSite->dispatch()
#19 /home/ahymsinc/public_html/main/libraries/cms/application/cms.php(252): JApplicationSite->doExecute()
#20 /home/ahymsinc/public_html/main/index.php(45): JApplicationCms->execute()
#21 {main}

***POST***
qfKey:              f0822554272aaf2cb87b427ebb7bb41f_6537
entryURL:           http://mandrillapp.com/track/click/30163280/ahymsin.org?p=eyJzIjoiOG15akJPOWlTUTVuaHFJUFgtaWxkcllNQzBJIiwidiI6MSwicCI6IntcInVcIjozMDE2MzI4MCxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvYWh5bXNpbi5vcmdcXFwvbWFpblxcXC9pbmRleC5waHA_b3B0aW9uPWNvbV9jaXZpY3JtJmFtcDt0YXNrPWNpdmljcm1cXFwvbWFpbGluZ1xcXC9mb3J3YXJkJmFtcDtoPTQ5OTQ2NmUxODZjYWIzMjUmYW1wO2ppZD0xNDgwJmFtcDtsYW5nPWVuJmFtcDtxaWQ9MzY3NzQxJmFtcDtyZXNldD0xXCIsXCJpZFwiOlwiMzc3OTNlZWZmMWE3NDA1NDg2ZGViYzRkNWM4M2FlODRcIixcInVybF9pZHNcIjpbXCI4MTViMjBiNjk1ZTIxNDhiYmQ2OWQ0NjgzNzhmYTQ2M2VjMzc5Zjg5XCJdfSJ9
_qf_default:        ForwardMailing:next
_qf_ForwardMailing_next:Forward
email_0:            happyluc2@videotron.ca
email_1:            minh__vo@hotmail.com
email_2:
email_3:
email_4:
forward_comment:
html_comment:

**Comment by JoeMurray** [comment]
Sorry for the delay in responding. Could you provide your CiviCRM version number, as the current head for the problematic line seems like it now is for a different version of this package: https://github.com/civicrm/civicrm-packages/blob/master/DB/msql.php#L241

**Comment by tabletguy** [comment]
I've been on the latest version of CiviCRM, which I believe is 4.6.
I'm still seeing a lot of various errors which always have mandrillapps as the HTTP_Referrer

But most of the errors are this, which might not be related to the form parameters error.

Array
(
    [message] => You do not have permission to access this page.
    [code] =>
)

I'd be happy to get you super admin access to the site if needed.

**Comment by MtnPavlas** [comment]
A "solution" to this is the set the 'Skip IDS check' permission for the Public user group to Allowed (at least in Joomla). Now, it's not really a secure solution... I'm simply saying what it's related to in order for someone to hopefully narrow down the troubleshooting. Thank you for looking into this.

**Comment by JoeMurray** [comment]
Could we get a specific point release, tabletguy, like 4.6.3 or 4.6.8. We need that to find the line in your version's code that is causing the error. You can find the specific version you have installed in /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/civicrm-version.txt

**Comment by tabletguy** [comment]
I update with each release and am currently at 4.6.8. 

Looks like it would be 4.6.5 based on file release dates at http://sourceforge.net/projects/civicrm/files/civicrm-stable/ for the date on this report.

However, I just now got another one, which of course should be 4.6.8 (current)

Again, site access can be made available if needed. Email to 'chinatablet' with Google's favorite email service.

There was a CiviCRM error at AHYMSIN.
Date: 2015-09-17T14:22:43-05:00

***ERROR***
Array
(
    [type] => 8
    [message] => Undefined index: shortCuts
    [file] => /home/ahymsinc/public_html/main/media/civicrm/templates_c/en_US/%%8B/8B6/8B6A05F3%%CreateNew.tpl.php
    [line] => 18
)
Array
(
    [message] => You do not have permission to access this page.
    [code] =>
)


***LOGGED IN USER***
contact_id:         19304
display_name:       Ahymsin Website Admin
email_id:           16109
email:              chinatablet@gmail.com
id:                 19304



***SERVER***
PATH:               /sbin:/usr/sbin:/bin:/usr/bin:/usr/X11R6/bin
PWD:                /usr/local/cpanel/cgi-sys
SHLVL:              0
SCRIPT_NAME:        /main/administrator/index.php
REQUEST_URI:        /main/administrator/?option=com_civicrm&task=civicrm/ajax/dashboard&op=get_widgets_by_column&key=8c079f6aa9ebde35aee825971c9a3597
QUERY_STRING:       option=com_civicrm&task=civicrm/ajax/dashboard&op=get_widgets_by_column&key=8c079f6aa9ebde35aee825971c9a3597
REQUEST_METHOD:     GET
SERVER_PROTOCOL:    HTTP/1.1
GATEWAY_INTERFACE:  CGI/1.1
REMOTE_PORT:        61409
SCRIPT_FILENAME:    /home/ahymsinc/public_html/main/administrator/index.php
SERVER_ADMIN:       webmaster@ahymsin.org
CONTEXT_DOCUMENT_ROOT:/home/ahymsinc/public_html
CONTEXT_PREFIX:
REQUEST_SCHEME:     http
DOCUMENT_ROOT:      /home/ahymsinc/public_html
REMOTE_ADDR:        24.118.243.218
SERVER_PORT:        80
SERVER_ADDR:        184.154.90.58
SERVER_NAME:        ahymsin.org
SERVER_SOFTWARE:    Apache
SERVER_SIGNATURE:
HTTP_CONNECTION:    close
HTTP_COOKIE:        1f52aa9aff775cd7782366c9e816bbae=aale95sfsc9c8gfer16vs50iq6
HTTP_REFERER:       http://mandrillapp.com/track/click/30163280/ahymsin.org?p=eyJzIjoiSnpZd19EeFJadzR3Vk9iQW5GZmNnWmQtR1NFIiwidiI6MSwicCI6IntcInVcIjozMDE2MzI4MCxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvYWh5bXNpbi5vcmdcXFwvbWFpblxcXC9hZG1pbmlzdHJhdG9yXFxcL2luZGV4LnBocD9vcHRpb249Y29tX2Npdmljcm1cIixcImlkXCI6XCIwMWYwYzdjZWFiYmM0ZjFjYWJiODI1Y2ZmZTlmZDYwZVwiLFwidXJsX2lkc1wiOltcIjhkMGM0ZmEzNzQ1N2MxYTAwNzMxZjAxNTY2MTQzNmY5ZTU3OGMzMzZcIl19In0
HTTP_X_REQUESTED_WITH:XMLHttpRequest
HTTP_DNT:           1
HTTP_ACCEPT_ENCODING:gzip, deflate
HTTP_ACCEPT_LANGUAGE:en-US,en;q=0.5
HTTP_ACCEPT:        application/json, text/javascript, */*; q=0.01
HTTP_USER_AGENT:    Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0
HTTP_HOST:          ahymsin.org
UNIQUE_ID:          VfsTA7iaWjoAAQgcD-gAAAAT
FCGI_ROLE:          RESPONDER
PHP_SELF:           /main/administrator/index.php
REQUEST_TIME_FLOAT: 1442517763.421
REQUEST_TIME:       1442517763



***BACKTRACE***
#0 /home/ahymsinc/public_html/main/media/civicrm/custom_ext/ca.bidon.reporterror/reporterror.php(207): reporterror_civicrm_generatereport("AHYMSIN", (Array:2), NULL)
#1 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Core/Error.php(351): reporterror_civicrm_handler((Array:2))
#2 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Utils/System/Joomla.php(455): CRM_Core_Error::fatal("You do not have permission to access this page.")
#3 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Utils/System.php(277): CRM_Utils_System_Joomla->permissionDenied()
#4 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(232): CRM_Utils_System::permissionDenied()
#5 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:12))
#6 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#7 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm.php(116): CRM_Core_Invoke::invoke((Array:3))
#8 /home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm.php(40): civicrm_invoke()
#9 /home/ahymsinc/public_html/main/libraries/cms/component/helper.php(392): require_once("/home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm.php")
#10 /home/ahymsinc/public_html/main/libraries/cms/component/helper.php(372): JComponentHelper::executeComponent("/home/ahymsinc/public_html/main/administrator/components/com_civicrm/civicrm.php")
#11 /home/ahymsinc/public_html/main/libraries/cms/application/administrator.php(98): JComponentHelper::renderComponent("com_civicrm")
#12 /home/ahymsinc/public_html/main/libraries/cms/application/administrator.php(152): JApplicationAdministrator->dispatch()
#13 /home/ahymsinc/public_html/main/libraries/cms/application/cms.php(252): JApplicationAdministrator->doExecute()
#14 /home/ahymsinc/public_html/main/administrator/index.php(47): JApplicationCms->execute()
#15 {main}


***POST***

**Comment by tabletguy** [comment]
Joomla 3.4.4 now as well.

**Comment by MtnPavlas** [comment]
hi guys, I'm on CiviCRM 4.6.8 w/ Joomla 3.4.3
even with the disabled IDS check (which I really am not a fan of and will re-enable shortly) I get some webhook failures and some successes

Please LMK what I can post for troubleshooting purposes

thank you!

**Comment by JoeMurray** [comment]
What is the url for the webhook callback that you have entered into Mandrill?

**Comment by pradpnayak** [comment]
Can you please update the extension and check if still get error

Here is the download link:
https://github.com/JMAConsulting/biz.jmaconsulting.mte/archive/v2.1.beta.zip
