### ISSUE TITLE
Mysql FK constraint violation 

### ISSUE THREAD

**Issue by shawnholt** [JMAConsulting/biz.jmaconsulting.mte#96]
I'm seeing some strange behavior and errors (listing here but not sure if related to FK constraint).  
1. I see occasional wehook failure 500 messages (and sometimes they process)
2. Sometimes the sender email is added as a duplicate contact (ie. events@domain.org has 450 contact records.)
3. Occasional error messages with stack trace related to FK constraints.  It looks like the email queue was deleted. errors are like this:
```

Oct 01 11:53:53  [info] $Fatal Error Details = Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => handle
        )

    [code] => -3
    [message] => DB Error: constraint violation
    [mode] => 16
    [debug_info] => INSERT INTO civicrm_mandrill_activity (mailing_queue_id , activity_id ) VALUES ( 26 ,  125 )  [nativecode=1452 ** Cannot add or update a child row: a foreign key constraint fails (`xxxxx_civi`.`civicrm_mandrill_activity`, CONSTRAINT `FK_civicrm_mandrill_activity_mailing_queue_id` FOREIGN KEY (`mailing_queue_id`) REFERENCES `civicrm_mailing_event_queue` (`id`) ON DELE)]
    [type] => DB_Error
    [user_info] => INSERT INTO civicrm_mandrill_activity (mailing_queue_id , activity_id ) VALUES ( 26 ,  125 )  [nativecode=1452 ** Cannot add or update a child row: a foreign key constraint fails (`xxxxx_civi`.`civicrm_mandrill_activity`, CONSTRAINT `FK_civicrm_mandrill_activity_mailing_queue_id` FOREIGN KEY (`mailing_queue_id`) REFERENCES `civicrm_mailing_event_queue` (`id`) ON DELE)]
    [to_string] => [db_error: message="DB Error: constraint violation" code=-3 mode=callback callback=CRM_Core_Error::handle prefix="" info="INSERT INTO civicrm_mandrill_activity (mailing_queue_id , activity_id ) VALUES ( 26 ,  125 )  [nativecode=1452 ** Cannot add or update a child row: a foreign key constraint fails (`xxxxx_civi`.`civicrm_mandrill_activity`, CONSTRAINT `FK_civicrm_mandrill_activity_mailing_queue_id` FOREIGN KEY (`mailing_queue_id`) REFERENCES `civicrm_mailing_event_queue` (`id`) ON DELE)]"]
)


Oct 01 11:53:53  [info] $backTrace = #0 /home/xxxxx/public_html/drupal/sites/all/modules/civicrm/CRM/Core/Error.php(235): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 [internal function](): CRM_Core_Error::handle(Object(DB_Error))
#2 /home/xxxxx/public_html/drupal/sites/all/modules/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error))
#3 /home/xxxxx/public_html/drupal/sites/all/modules/civicrm/packages/DB.php(976): PEAR_Error->PEAR_Error("DB Error: constraint violation", -3, 16, (Array:2), "INSERT INTO civicrm_mandrill_activity (mailing_queue_id , activity_id ) VALUE...")
#4 /home/xxxxx/public_html/drupal/sites/all/modules/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-3, 16, (Array:2), "INSERT INTO civicrm_mandrill_activity (mailing_queue_id , activity_id ) VALUE...")
#5 /home/xxxxx/public_html/drupal/sites/all/modules/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -3, NULL, NULL, "INSERT INTO civicrm_mandrill_activity (mailing_queue_id , activity_id ) VALUE...", "DB_Error", TRUE)
#6 /home/xxxxx/public_html/drupal/sites/all/modules/civicrm/packages/DB/mysql.php(895): DB_common->raiseError(-3, NULL, NULL, NULL, "1452 ** Cannot add or update a child row: a foreign key constraint fails (`ch...")
#7 /home/xxxxx/public_html/drupal/sites/all/modules/civicrm/packages/DB/mysql.php(328): DB_mysql->mysqlRaiseError()
#8 /home/xxxxx/public_html/drupal/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("INSERT INTO civicrm_mandrill_activity (mailing_queue_id , activity_id ) VALUE...")
#9 /home/xxxxx/public_html/drupal/sites/all/modules/civicrm/packages/DB/DataObject.php(2442): DB_common->query("INSERT INTO civicrm_mandrill_activity (mailing_queue_id , activity_id ) VALUE...")
#10 /home/xxxxx/public_html/drupal/sites/all/modules/civicrm/packages/DB/DataObject.php(1060): DB_DataObject->_query("INSERT INTO civicrm_mandrill_activity (mailing_queue_id , activity_id ) VALUE...")
#11 /home/xxxxx/public_html/drupal/sites/all/modules/civicrm/CRM/Core/DAO.php(450): DB_DataObject->insert()
#12 /home/xxxxx/public_html/drupal/sites/default/files/civicrm/extensions/biz.jmaconsulting.mte/CRM/Mte/BAO/MandrillActivity.php(50): CRM_Core_DAO->save()
#13 /home/xxxxx/public_html/drupal/sites/default/files/civicrm/extensions/biz.jmaconsulting.mte/CRM/Mte/BAO/Mandrill.php(128): CRM_Mte_BAO_MandrillActivity::create((Array:2))
#14 /home/xxxxx/public_html/drupal/sites/default/files/civicrm/extensions/biz.jmaconsulting.mte/CRM/Mte/Page/callback.php(50): CRM_Mte_BAO_Mandrill::processMandrillCalls((Array:26))
#15 /home/xxxxx/public_html/drupal/sites/all/modules/civicrm/CRM/Core/Invoke.php(312): CRM_Mte_Page_callback->run((Array:4), NULL)
#16 /home/xxxxx/public_html/drupal/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:13))
#17 /home/xxxxx/public_html/drupal/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:4))
#18 /home/xxxxx/public_html/drupal/sites/all/modules/civicrm/drupal/civicrm.module(489): CRM_Core_Invoke::invoke((Array:4))
#19 [internal function](): civicrm_invoke("ajax", "mte", "callback")
#20 /home/xxxxx/public_html/drupal/includes/menu.inc(519): call_user_func_array("civicrm_invoke", (Array:3))
#21 /home/xxxxx/public_html/drupal/index.php(21): menu_execute_active_handler()
#22 {main}

```

**Comment by pradpnayak** [comment]
Can you please update the extension and check if still get error

Here is the download link:
https://github.com/JMAConsulting/biz.jmaconsulting.mte/archive/v2.1.beta.zip
